name: My Starter Workflow

on:
  push:
    branches: [ main ]

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]  # 定义要测试的Node.js版本列表
    
    # 调用可重用工作流，并传递矩阵变量
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: ${{ matrix.nodeversion }}  # 动态传递当前矩阵变量值
