name: My Starter Workflow

on:
  push:
    branches: [ main ]

jobs:
  # 其他已存在的作业（如果有）
  
  call-reusable-workflow:  # 新作业名称，可自定义
    uses: ./.github/workflows/reusable-workflow.yml  # 指定可重用工作流路径
    with:
      node: 14  # 传递必需的node参数，值为"14"
